### ISSUE TITLE
 The buttons on the front page (i.e. "Get Involved"), where do they navigate to?

### ISSUE THREAD

**Issue by marwahaha** [tgeorgeux/new.jupyter.github.io#50]

**Comment by tgeorgeux** [comment]
All the links are on the prototype: https://www.figma.com/proto/PQD2GrejGoeZdYGhXthnAuEs/jupyter_master?node-id=1804%3A10&viewport=367%2C529%2C0.14759419858455658&scaling=min-zoom

**Comment by marwahaha** [comment]
Ok, links have been added for the Home and About sections
